name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node/

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          RESEND_API_KEY: ${{ vars.RESEND_API_KEY }}
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel
        id: deploy
        run: |
          npx vercel --prod --token ${{ vars.VERCEL_TOKEN }} || echo "Deployment failed" >> $GITHUB_ENV

      - name: Check deployment status
        run: |
          if [[ "${{ steps.deploy.outputs }}" == *"error"* ]]; then
            echo "Deployment failed. Initiating rollback."
            npx vercel rollback --token ${{ vars.VERCEL_TOKEN }} || echo "Rollback failed."
          else
            echo "Deployment successful."
          fi
  
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/staging'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Deploy and Alias to Staging Domain
        id: deploy-to-staging
        run: |
          DEPLOY_URL=$(vercel --token ${{ vars.VERCEL_TOKEN }} --yes)
          vercel alias $DEPLOY_URL staging-group-bse-24-11.vercel.app --token ${{ vars.VERCEL_TOKEN}}
        env:
          VERCEL_TOKEN: ${{ vars.VERCEL_TOKEN }}
          